Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  
Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 11


